#!/bin/bash
make ARCH=riscv64-nemu update
mv /home/guodl/Desktop/ysyx/ysyx-workbench/ics2022/navy-apps/build/ramdisk.img /home/guodl/Desktop/ysyx/ysyx-workbench/ics2022/nanos-lite/build/ramdisk.img
cd /home/guodl/Desktop/ysyx/ysyx-workbench/ics2022/nanos-lite
make make ARCH=riscv64-nemu run



